/* eslint-disable @typescript-eslint/restrict-template-expressions */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-misused-promises */
import CopyIcon from "@/components/Icons/Copy.icon";
import PlusIcon from "@/components/Icons/Plus.icon";
import Loader from "@/components/Loader";
import Text from "@/components/Typography/text";
import { cn } from "@/utils/className";
import { Expletus_Sans, Poppins } from "next/font/google";
import Head from "next/head";
import { useState, type FormEvent } from "react";
import { Toaster, toast } from "react-hot-toast";

const expletus = Expletus_Sans({
  display: "swap",
  variable: "--expletus-sans",
  subsets: ["latin-ext"],
});

const poppins = Poppins({
  display: "swap",
  variable: "--poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export default function Home() {
  const [shortened, setShortened] = useState<string>("");
  const [shortening, setShortening] = useState<boolean>(false);

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const url = `${(e.target as any)?.["url"]?.value}`;
    setShortening(true);
    setTimeout(() => {
      setShortened((prev) => (!prev ? `https://peq.nu/${url.slice(-4)}` : ""));
      setShortening(false);
    }, 2000);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(shortened);
    toast.success("Link copiado para área de transferência!", {
      icon: "📋",
    });
  };

  return (
    <>
      <Head>
        <title>peq.nu encurtador</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={cn(
          "flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-background to-dark",
          expletus.className,
          poppins.className
        )}
      >
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <Text as="h1" className="font-expletus text-white" size="8xl">
            peq.nu
          </Text>
          <div>
            <form onSubmit={handleSubmit}>
              <div className="group relative w-[600px] max-w-[95vw] overflow-hidden rounded-full lg:max-w-[600px]">
                <input
                  id="url"
                  name="url"
                  placeholder="Coloque aqui seu link grande"
                  className={cn(
                    "mr-[100px] h-10 w-full rounded-full px-3",
                    "border border-gray-700 bg-[#223733] text-white",
                    "text-center font-expletus placeholder:text-gray-400"
                  )}
                />
                <button
                  type="submit"
                  className={cn(
                    "-ml-8 h-10 rounded-full bg-primary px-8 font-poppins font-semibold text-white",
                    "absolute right-0 top-0 max-w-full"
                  )}
                >
                  {shortening ? (
                    <Loader />
                  ) : (
                    <Text as="span" size="lg">
                      Encurtar
                    </Text>
                  )}
                </button>
                <div
                  className={cn(
                    "absolute right-0 top-0 z-20 h-10 w-full rounded-full",
                    "bg-primary text-white",
                    "flex items-center justify-center gap-3",
                    "translate-x-1/2 scale-x-0 transition-all",
                    !!shortened && "translate-x-0 scale-x-100"
                  )}
                >
                  <Text as="span" size="lg">
                    {shortened}
                  </Text>
                  <div className="absolute right-5 flex items-center gap-4">
                    <button
                      type="button"
                      onClick={() => handleCopy()}
                      title="Copiar para área de transferência"
                    >
                      <CopyIcon />
                    </button>
                    <button
                      type="button"
                      onClick={() => setShortened("")}
                      title="Gerar novo link encurtado"
                    >
                      <PlusIcon />
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </main>
      <Toaster />
    </>
  );
}
